-- Backup of travel_deals table structure
CREATE TABLE travel_deals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    price TEXT NOT NULL,
    originalPrice TEXT,
    currency TEXT DEFAULT 'INR',
    imageUrl TEXT NOT NULL,
    affiliateUrl TEXT NOT NULL,
    originalUrl TEXT,
    category TEXT DEFAULT 'travel',
    subcategory TEXT,
    travelType TEXT,
    partner TEXT,
    validTill TEXT,
    route TEXT,
    duration TEXT,
    rating REAL,
    reviewCount INTEGER,
    source TEXT DEFAULT 'sample_data',
    telegramMessageId INTEGER,
    telegramChannelId INTEGER,
    processingStatus TEXT DEFAULT 'active',
    createdAt INTEGER DEFAULT (strftime('%s', 'now')),
    updatedAt INTEGER DEFAULT (strftime('%s', 'now'))
  );

-- Backup of travel_picks_products table structure
CREATE TABLE travel_picks_products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            price TEXT,
            original_price TEXT,
            currency TEXT DEFAULT 'INR',
            image_url TEXT,
            affiliate_url TEXT,
            original_url TEXT,
            category TEXT,
            rating REAL DEFAULT 0,
            review_count INTEGER DEFAULT 0,
            discount INTEGER DEFAULT 0,
            is_new INTEGER DEFAULT 1,
            is_featured INTEGER DEFAULT 0,
            affiliate_network TEXT,
            telegram_message_id INTEGER,
            telegram_channel_id INTEGER,
            telegram_channel_name TEXT,
            processing_status TEXT DEFAULT 'active',
            content_type TEXT DEFAULT 'product',
            affiliate_tag_applied INTEGER DEFAULT 1,
            created_at INTEGER DEFAULT (strftime('%s', 'now')),
            updated_at INTEGER DEFAULT (strftime('%s', 'now')),
            expires_at INTEGER,
            click_count INTEGER DEFAULT 0,
            conversion_count INTEGER DEFAULT 0,
            display_pages TEXT,
            source_metadata TEXT,
            tags TEXT,
            has_limited_offer INTEGER DEFAULT 0,
            limited_offer_text TEXT,
            message_group_id TEXT,
            product_sequence INTEGER,
            total_in_group INTEGER,
            affiliate_config TEXT
          );

-- Backup of travel_categories table structure
CREATE TABLE travel_categories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      icon TEXT NOT NULL,
      color TEXT NOT NULL,
      description TEXT,
      isActive INTEGER DEFAULT 1,
      displayOrder INTEGER DEFAULT 0,
      createdAt INTEGER DEFAULT (strftime('%s', 'now')),
      updatedAt INTEGER DEFAULT (strftime('%s', 'now'))
    );
