CREATE TABLE `admin_users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`username` text NOT NULL,
	`email` text NOT NULL,
	`password_hash` text NOT NULL,
	`reset_token` text,
	`reset_token_expiry` integer,
	`last_login` integer,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.096Z"',
	`is_active` integer DEFAULT true
);
--> statement-breakpoint
CREATE UNIQUE INDEX `admin_users_username_unique` ON `admin_users` (`username`);--> statement-breakpoint
CREATE UNIQUE INDEX `admin_users_email_unique` ON `admin_users` (`email`);--> statement-breakpoint
CREATE TABLE `affiliate_networks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`slug` text NOT NULL,
	`description` text NOT NULL,
	`commission_rate` numeric NOT NULL,
	`tracking_params` text,
	`logo_url` text,
	`is_active` integer DEFAULT true,
	`join_url` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `affiliate_networks_slug_unique` ON `affiliate_networks` (`slug`);--> statement-breakpoint
CREATE TABLE `announcements` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`message` text NOT NULL,
	`is_active` integer DEFAULT true,
	`text_color` text DEFAULT '#ffffff',
	`background_color` text DEFAULT '#3b82f6',
	`font_size` text DEFAULT '16px',
	`font_weight` text DEFAULT 'normal',
	`text_decoration` text DEFAULT 'none',
	`font_style` text DEFAULT 'normal',
	`animation_speed` text DEFAULT '30',
	`text_border_width` text DEFAULT '0px',
	`text_border_style` text DEFAULT 'solid',
	`text_border_color` text DEFAULT '#000000',
	`banner_border_width` text DEFAULT '0px',
	`banner_border_style` text DEFAULT 'solid',
	`banner_border_color` text DEFAULT '#000000',
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.096Z"'
);
--> statement-breakpoint
CREATE TABLE `apps_products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`price` text,
	`original_price` text,
	`currency` text DEFAULT 'INR',
	`image_url` text,
	`affiliate_url` text NOT NULL,
	`original_url` text,
	`category` text,
	`subcategory` text,
	`rating` text,
	`review_count` text,
	`discount` text,
	`is_featured` integer DEFAULT false,
	`is_new` integer DEFAULT true,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`has_limited_offer` integer DEFAULT false,
	`limited_offer_text` text,
	`affiliate_network` text DEFAULT 'apps',
	`affiliate_network_id` integer,
	`affiliate_tag_applied` integer DEFAULT true,
	`commission_rate` real,
	`telegram_message_id` integer,
	`telegram_channel_id` text,
	`processing_status` text DEFAULT 'active',
	`message_group_id` text,
	`product_sequence` integer DEFAULT 1,
	`total_in_group` integer DEFAULT 1,
	`is_ai_app` integer DEFAULT false,
	`is_service` integer DEFAULT false,
	`app_type` text DEFAULT 'mobile',
	`platform` text,
	`app_size` text,
	`app_version` text,
	`developer_name` text,
	`pricing_type` text DEFAULT 'one-time',
	`monthly_price` text,
	`yearly_price` text,
	`is_free` integer DEFAULT false,
	`price_description` text,
	`ai_category` text,
	`ai_features` text,
	`model_type` text,
	`api_access` integer DEFAULT false,
	`app_store_url` text,
	`play_store_url` text,
	`web_app_url` text,
	`download_url` text,
	`source_domain` text,
	`source_metadata` text,
	`scraping_method` text DEFAULT 'telegram',
	`click_count` integer DEFAULT 0,
	`conversion_count` integer DEFAULT 0,
	`view_count` integer DEFAULT 0,
	`download_count` integer DEFAULT 0,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`expires_at` integer,
	`display_pages` text DEFAULT 'apps',
	`display_order` integer DEFAULT 0,
	`gender` text,
	`content_type` text DEFAULT 'app',
	`source` text DEFAULT 'telegram'
);
--> statement-breakpoint
CREATE TABLE `blog_posts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text NOT NULL,
	`excerpt` text NOT NULL,
	`content` text NOT NULL,
	`category` text NOT NULL,
	`tags` text,
	`image_url` text NOT NULL,
	`video_url` text,
	`published_at` integer NOT NULL,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.095Z"',
	`read_time` text NOT NULL,
	`slug` text NOT NULL,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer
);
--> statement-breakpoint
CREATE TABLE `canva_posts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`content_type` text NOT NULL,
	`content_id` integer NOT NULL,
	`design_id` text,
	`template_id` text,
	`caption` text,
	`hashtags` text,
	`platforms` text,
	`post_urls` text,
	`status` text DEFAULT 'pending',
	`scheduled_at` integer,
	`posted_at` integer,
	`expires_at` integer,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"'
);
--> statement-breakpoint
CREATE TABLE `canva_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`is_enabled` integer DEFAULT false,
	`api_key` text,
	`api_secret` text,
	`default_template_id` text,
	`auto_generate_captions` integer DEFAULT true,
	`auto_generate_hashtags` integer DEFAULT true,
	`default_title` text,
	`default_caption` text,
	`default_hashtags` text,
	`platforms` text DEFAULT '[]',
	`schedule_type` text DEFAULT 'immediate',
	`schedule_delay_minutes` integer DEFAULT 0,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"'
);
--> statement-breakpoint
CREATE TABLE `canva_templates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`template_id` text NOT NULL,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`category` text,
	`thumbnail_url` text,
	`is_active` integer DEFAULT true,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"'
);
--> statement-breakpoint
CREATE UNIQUE INDEX `canva_templates_template_id_unique` ON `canva_templates` (`template_id`);--> statement-breakpoint
CREATE TABLE `categories` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`icon` text NOT NULL,
	`color` text NOT NULL,
	`description` text NOT NULL,
	`parent_id` integer,
	`is_for_products` integer DEFAULT true,
	`is_for_services` integer DEFAULT false,
	`is_for_ai_apps` integer DEFAULT false,
	`display_order` integer DEFAULT 0,
	FOREIGN KEY (`parent_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `currency_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`default_currency` text DEFAULT 'INR',
	`enabled_currencies` text DEFAULT '["INR","USD","EUR","GBP","JPY","CAD","AUD","SGD","CNY","KRW"]',
	`auto_update_rates` integer DEFAULT true,
	`last_rate_update` integer,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.098Z"'
);
--> statement-breakpoint
CREATE TABLE `deals_hub_products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`price` text,
	`original_price` text,
	`currency` text DEFAULT 'INR',
	`image_url` text,
	`affiliate_url` text NOT NULL,
	`original_url` text,
	`category` text,
	`subcategory` text,
	`rating` text,
	`review_count` text,
	`discount` text,
	`is_featured` integer DEFAULT false,
	`is_new` integer DEFAULT true,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`has_limited_offer` integer DEFAULT false,
	`limited_offer_text` text,
	`affiliate_network` text DEFAULT 'deals-hub',
	`affiliate_network_id` integer,
	`affiliate_tag_applied` integer DEFAULT true,
	`commission_rate` real,
	`telegram_message_id` integer,
	`telegram_channel_id` text,
	`processing_status` text DEFAULT 'active',
	`message_group_id` text,
	`product_sequence` integer DEFAULT 1,
	`total_in_group` integer DEFAULT 1,
	`deal_type` text DEFAULT 'general',
	`deal_priority` integer DEFAULT 0,
	`deal_start_time` integer,
	`deal_end_time` integer,
	`stock_quantity` integer,
	`max_quantity_per_user` integer DEFAULT 1,
	`source_domain` text,
	`source_metadata` text,
	`scraping_method` text DEFAULT 'telegram',
	`click_count` integer DEFAULT 0,
	`conversion_count` integer DEFAULT 0,
	`view_count` integer DEFAULT 0,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`expires_at` integer,
	`display_pages` text DEFAULT 'deals-hub',
	`display_order` integer DEFAULT 0,
	`gender` text,
	`content_type` text DEFAULT 'product',
	`source` text DEFAULT 'telegram'
);
--> statement-breakpoint
CREATE TABLE `exchange_rates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`from_currency` text NOT NULL,
	`to_currency` text NOT NULL,
	`rate` numeric NOT NULL,
	`last_updated` integer DEFAULT '"2025-09-05T12:52:58.098Z"'
);
--> statement-breakpoint
CREATE TABLE `global_picks_products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`price` text,
	`original_price` text,
	`currency` text DEFAULT 'INR',
	`image_url` text,
	`affiliate_url` text NOT NULL,
	`original_url` text,
	`category` text,
	`subcategory` text,
	`rating` text,
	`review_count` text,
	`discount` text,
	`is_featured` integer DEFAULT false,
	`is_new` integer DEFAULT true,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`has_limited_offer` integer DEFAULT false,
	`limited_offer_text` text,
	`affiliate_network` text DEFAULT 'global-picks',
	`affiliate_network_id` integer,
	`affiliate_tag_applied` integer DEFAULT true,
	`commission_rate` real,
	`telegram_message_id` integer,
	`telegram_channel_id` text,
	`processing_status` text DEFAULT 'active',
	`message_group_id` text,
	`product_sequence` integer DEFAULT 1,
	`total_in_group` integer DEFAULT 1,
	`source_domain` text,
	`source_metadata` text,
	`scraping_method` text DEFAULT 'universal',
	`click_count` integer DEFAULT 0,
	`conversion_count` integer DEFAULT 0,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`expires_at` integer,
	`display_pages` text DEFAULT 'global-picks',
	`display_order` integer DEFAULT 0,
	`gender` text,
	`content_type` text DEFAULT 'product',
	`source` text DEFAULT 'telegram'
);
--> statement-breakpoint
CREATE TABLE `loot_box_products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`price` text,
	`original_price` text,
	`currency` text DEFAULT 'INR',
	`image_url` text,
	`affiliate_url` text NOT NULL,
	`original_url` text,
	`category` text,
	`subcategory` text,
	`rating` text,
	`review_count` text,
	`discount` text,
	`is_featured` integer DEFAULT false,
	`is_new` integer DEFAULT true,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`has_limited_offer` integer DEFAULT false,
	`limited_offer_text` text,
	`affiliate_network` text DEFAULT 'deodap',
	`affiliate_network_id` integer,
	`affiliate_tag_applied` integer DEFAULT true,
	`commission_rate` real,
	`telegram_message_id` integer,
	`telegram_channel_id` text,
	`processing_status` text DEFAULT 'active',
	`message_group_id` text,
	`product_sequence` integer DEFAULT 1,
	`total_in_group` integer DEFAULT 1,
	`product_type` text DEFAULT 'product',
	`deodap_category` text,
	`is_service` integer DEFAULT false,
	`is_digital` integer DEFAULT false,
	`is_course` integer DEFAULT false,
	`service_duration` text,
	`access_type` text,
	`deodap_product_id` text,
	`deodap_seller` text,
	`deodap_tags` text,
	`source_domain` text DEFAULT 'deodap.in',
	`source_metadata` text,
	`scraping_method` text DEFAULT 'telegram',
	`click_count` integer DEFAULT 0,
	`conversion_count` integer DEFAULT 0,
	`view_count` integer DEFAULT 0,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`expires_at` integer,
	`display_pages` text DEFAULT 'loot-box',
	`display_order` integer DEFAULT 0,
	`gender` text,
	`content_type` text DEFAULT 'product',
	`source` text DEFAULT 'telegram'
);
--> statement-breakpoint
CREATE TABLE `newsletter_subscribers` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`email` text NOT NULL,
	`subscribed_at` integer DEFAULT '"2025-09-05T12:52:58.095Z"'
);
--> statement-breakpoint
CREATE UNIQUE INDEX `newsletter_subscribers_email_unique` ON `newsletter_subscribers` (`email`);--> statement-breakpoint
CREATE TABLE `products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`description` text NOT NULL,
	`price` numeric NOT NULL,
	`original_price` numeric,
	`currency` text DEFAULT 'INR',
	`image_url` text NOT NULL,
	`affiliate_url` text NOT NULL,
	`affiliate_network_id` integer,
	`category` text NOT NULL,
	`subcategory` text,
	`gender` text,
	`rating` numeric NOT NULL,
	`review_count` integer NOT NULL,
	`discount` integer,
	`is_new` integer DEFAULT false,
	`is_featured` integer DEFAULT false,
	`is_service` integer DEFAULT false,
	`is_ai_app` integer DEFAULT false,
	`custom_fields` text,
	`pricing_type` text,
	`monthly_price` text,
	`yearly_price` text,
	`is_free` integer DEFAULT false,
	`price_description` text,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`source` text,
	`telegram_message_id` integer,
	`expires_at` integer,
	`affiliate_link` text,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.095Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.095Z"',
	`display_pages` text DEFAULT '["home"]',
	FOREIGN KEY (`affiliate_network_id`) REFERENCES `affiliate_networks`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `top_picks_products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`price` text,
	`original_price` text,
	`currency` text DEFAULT 'INR',
	`image_url` text,
	`affiliate_url` text NOT NULL,
	`original_url` text,
	`category` text,
	`subcategory` text,
	`rating` text,
	`review_count` text,
	`discount` text,
	`is_featured` integer DEFAULT false,
	`is_new` integer DEFAULT true,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`has_limited_offer` integer DEFAULT false,
	`limited_offer_text` text,
	`affiliate_network` text DEFAULT 'top-picks',
	`affiliate_network_id` integer,
	`affiliate_tag_applied` integer DEFAULT true,
	`commission_rate` real,
	`telegram_message_id` integer,
	`telegram_channel_id` text,
	`processing_status` text DEFAULT 'active',
	`message_group_id` text,
	`product_sequence` integer DEFAULT 1,
	`total_in_group` integer DEFAULT 1,
	`is_viral` integer DEFAULT false,
	`is_trending` integer DEFAULT false,
	`is_limited_deal` integer DEFAULT false,
	`is_new_offer` integer DEFAULT false,
	`trend_score` real DEFAULT 0,
	`viral_score` real DEFAULT 0,
	`popularity_rank` integer DEFAULT 0,
	`view_velocity` real DEFAULT 0,
	`click_velocity` real DEFAULT 0,
	`share_count` integer DEFAULT 0,
	`wishlist_count` integer DEFAULT 0,
	`conversion_velocity` real DEFAULT 0,
	`trending_start_time` integer,
	`trending_duration` integer,
	`peak_performance_time` integer,
	`deal_urgency_level` text DEFAULT 'normal',
	`stock_level` text,
	`deal_expires_at` integer,
	`flash_sale` integer DEFAULT false,
	`recent_purchases` integer DEFAULT 0,
	`social_mentions` integer DEFAULT 0,
	`influencer_endorsed` integer DEFAULT false,
	`quality_score` real DEFAULT 0,
	`user_satisfaction` real DEFAULT 0,
	`return_rate` real DEFAULT 0,
	`source_domain` text,
	`source_page` text,
	`source_metadata` text,
	`scraping_method` text DEFAULT 'telegram',
	`click_count` integer DEFAULT 0,
	`conversion_count` integer DEFAULT 0,
	`view_count` integer DEFAULT 0,
	`share_count_total` integer DEFAULT 0,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`updated_at` integer DEFAULT '"2025-09-05T12:52:58.099Z"',
	`expires_at` integer,
	`last_trending_check` integer,
	`display_pages` text DEFAULT 'top-picks',
	`display_order` integer DEFAULT 0,
	`priority_level` integer DEFAULT 1,
	`gender` text,
	`content_type` text DEFAULT 'product',
	`source` text DEFAULT 'telegram',
	`is_service` integer DEFAULT false,
	`is_ai_app` integer DEFAULT false,
	`app_type` text,
	`platform` text
);
--> statement-breakpoint
CREATE TABLE `video_content` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`video_url` text NOT NULL,
	`thumbnail_url` text,
	`platform` text NOT NULL,
	`category` text NOT NULL,
	`tags` text,
	`duration` text,
	`has_timer` integer DEFAULT false,
	`timer_duration` integer,
	`timer_start_time` integer,
	`pages` text DEFAULT '[]',
	`show_on_homepage` integer DEFAULT true,
	`cta_text` text,
	`cta_url` text,
	`created_at` integer DEFAULT '"2025-09-05T12:52:58.096Z"'
);
