name: Deploy PickNTrust to AWS EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 51.20.43.157
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to application directory
          cd /home/ubuntu/PickNTrust || exit 1
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Build application
          npm run build
          
          # Restart PM2 process
          pm2 restart pickntrust || pm2 start npm --name "pickntrust" -- start
          
          # Save PM2 configuration
          pm2 save
          
          # Check status
          pm2 status
          
          echo "Deployment completed successfully!"

    - name: Verify deployment
      run: |
        sleep 30
        curl -f http://51.20.43.157 || exit 1
        echo "Application is running successfully!"
